### ISSUE TITLE
請教參數設置問題。

### ISSUE THREAD

**Issue by zhi8617** [omnipay-taiwan/omnipay-ecpay#1]
https://github.com/omnipay-taiwan/omnipay-ecpay/blob/3364b42b7e42ebeafa8c6e2a7aa76ae43b444e90/src/Message/PurchaseRequest.php#L208

請問 purchase  請求中, 您將 ClientRedirectURL  參數放在 SendExtend  裡面 ，
導致選號之後會停在綠界。 我記得是放在主要參數裡面 。

請問您有試過這段嗎 ??

**Comment by recca0120** [comment]
https://github.com/omnipay-taiwan/omnipay-ecpay/blob/master/lib/ECPayAIO_PHP/AioSDK/sdk/ECPay.Payment.Integration.php#L1484

它原始程式碼就是在 extend 裡了喔

**Comment by zhi8617** [comment]
感謝您製作套件，開心寫完測試，後發現畫面會停在綠界
我後來 dump送給綠界的表單   ClientRedirectURL 數值是 null , 
謝謝您回覆，我在查察看看什麼原因。 （有可能是綠界或是我的問題）

**Comment by recca0120** [comment]
應該是看錯參數了，參數應該是ClientBackURL
https://github.com/omnipay-taiwan/omnipay-ecpay/blob/master/src/Message/PurchaseRequest.php#L71

這就是綠界讓人很頭痛的地方，參數命名很類似所以有時候會很難在第一時間分辨出來
